# Generated by Django 3.2.9 on 2021-11-27 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('PPRTD_weight', models.DecimalField(decimal_places=4, max_digits=5)),
                ('PFVIR_weight', models.DecimalField(decimal_places=4, max_digits=5)),
                ('department_indicator', models.DecimalField(decimal_places=1, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('units', models.CharField(max_length=255)),
                ('comment', models.TextField()),
                ('target_indicator', models.DecimalField(decimal_places=1, max_digits=4)),
                ('actual_indicator', models.DecimalField(decimal_places=1, max_digits=4)),
                ('Significance_of_indicator', models.DecimalField(decimal_places=4, max_digits=5)),
                ('Plan', models.DecimalField(decimal_places=1, max_digits=4)),
                ('Degree_of_compliance', models.DecimalField(decimal_places=1, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('target_indicator_IUC', models.DecimalField(decimal_places=2, max_digits=5)),
                ('actual_indicator_IUC', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
