# Generated by Django 3.2.9 on 2021-11-27 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IC', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='IC.service'),
        ),
        migrations.AlterField(
            model_name='department',
            name='department_indicator',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='actual_indicator',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='service',
            name='actual_indicator_IUC',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
