# Generated by Django 3.2.9 on 2021-11-27 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IC', '0002_auto_20211128_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='IC.department'),
        ),
    ]
