# Generated by Django 3.2.9 on 2021-12-15 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IC', '0003_indicator_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='PFVIR_indicator',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='department',
            name='PPRTD_indicator',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='department',
            name='PFVIR_weight',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='department',
            name='PPRTD_weight',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='Degree_of_compliance',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='Plan',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='target_indicator',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='service',
            name='target_indicator_IUC',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
