# Generated by Django 3.2.9 on 2022-01-14 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IC', '0005_indicator_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='actual_indicator_IUC',
            new_name='indicator_RTD',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='service',
            name='target_indicator_IUC',
        ),
        migrations.AddField(
            model_name='service',
            name='indicator_VIR',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
