# Generated by Django 3.2.8 on 2022-01-31 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IC', '0006_auto_20220114_2218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Critical_service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('working_mode_days', models.DecimalField(decimal_places=0, default=0, max_digits=1, null=True)),
                ('working_mode_hours', models.DecimalField(decimal_places=0, default=0, max_digits=2, null=True)),
                ('working_days_period', models.DecimalField(decimal_places=0, default=0, max_digits=2, null=True)),
                ('Operating_time_plan', models.DecimalField(decimal_places=0, default=0, max_digits=3, null=True)),
                ('Operating_time_actual', models.DecimalField(decimal_places=0, default=0, max_digits=3, null=True)),
                ('Completion_rate', models.DecimalField(decimal_places=2, default=0, max_digits=3, null=True)),
                ('Service_ownership', models.CharField(max_length=255)),
            ],
        ),
    ]
