# Generated by Django 3.2.8 on 2022-01-31 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IC', '0007_critical_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='critical_service',
            name='Operating_time_actual',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='critical_service',
            name='Operating_time_plan',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=4, null=True),
        ),
    ]
