# Generated by Django 3.2.8 on 2022-01-31 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IC', '0008_auto_20220131_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='critical_service',
            name='Completion_rate',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=4, null=True),
        ),
    ]
