# Generated by Django 3.2.8 on 2022-02-03 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IC', '0009_alter_critical_service_completion_rate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='critical_service',
            options={'ordering': ['title'], 'verbose_name': 'Критически важные сервисы/службы', 'verbose_name_plural': 'Критически важные сервисы/службы'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['service', 'title'], 'verbose_name': 'Отделы/группы', 'verbose_name_plural': 'Отделы/группы'},
        ),
        migrations.AlterModelOptions(
            name='indicator',
            options={'ordering': ['department', 'title'], 'verbose_name': 'Показатели', 'verbose_name_plural': 'Показатели'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['title'], 'verbose_name': 'Служба(уточнить название раздела)', 'verbose_name_plural': 'Служба(уточнить название раздела)'},
        ),
        migrations.AlterField(
            model_name='critical_service',
            name='Completion_rate',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=4, null=True, verbose_name='Выполнение'),
        ),
        migrations.AlterField(
            model_name='critical_service',
            name='Operating_time_actual',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=4, null=True, verbose_name='Факт, ч'),
        ),
        migrations.AlterField(
            model_name='critical_service',
            name='Operating_time_plan',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=4, null=True, verbose_name='План, ч'),
        ),
        migrations.AlterField(
            model_name='critical_service',
            name='Service_ownership',
            field=models.CharField(max_length=255, verbose_name='Принадлежность'),
        ),
        migrations.AlterField(
            model_name='critical_service',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='critical_service',
            name='working_days_period',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2, null=True, verbose_name='Рабочих дней в отчётном периоде'),
        ),
        migrations.AlterField(
            model_name='critical_service',
            name='working_mode_days',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=1, null=True, verbose_name='Рабочих дней в неделю'),
        ),
        migrations.AlterField(
            model_name='critical_service',
            name='working_mode_hours',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2, null=True, verbose_name='Рабочих часов в день'),
        ),
        migrations.AlterField(
            model_name='department',
            name='PFVIR_indicator',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='ПФВИР Показатель'),
        ),
        migrations.AlterField(
            model_name='department',
            name='PFVIR_weight',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=5, verbose_name='Вес, приоритет функционирование ВИР'),
        ),
        migrations.AlterField(
            model_name='department',
            name='PPRTD_indicator',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='ППРТД Показатель'),
        ),
        migrations.AlterField(
            model_name='department',
            name='PPRTD_weight',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=5, verbose_name='Вес, приоритет передача режимно- технологических данных'),
        ),
        migrations.AlterField(
            model_name='department',
            name='department_indicator',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='Показатель'),
        ),
        migrations.AlterField(
            model_name='department',
            name='title',
            field=models.TextField(verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='Degree_of_compliance',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='Выполнение'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='Plan',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='План'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='Significance_of_indicator',
            field=models.DecimalField(decimal_places=4, max_digits=5, verbose_name='Вес показателя'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='actual_indicator',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='Фактический показатель'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='comment',
            field=models.TextField(verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='target_indicator',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='Целевой показатель'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='units',
            field=models.CharField(max_length=255, verbose_name='Единицы измерения'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
    ]
